### PR TITLE
Update semc-install to pass options to installer

### PR DESCRIPTION
**Pull request by RhinoCodes**

### CODE REVIEW

**Comment by RhinoCodes** [comment]
@Bobbbay here's another one!

**Comment by bobbbay** [comment]
Awesome, but I'm honestly against grabbing an `install.sh`, what if the user has an `install.sh` in the directory already?

**Comment by RhinoCodes** [comment]
@Bobbbay true, ill do some quick testing and revise the PR

**Comment by bobbbay** [comment]
Cool! I could recommend writing an `install.yes.sh` in the github.io, and then curl it accordingly, but that would be messy imo.

**Comment by RhinoCodes** [comment]
ok @Bobbbay all fixed

**Comment by bobbbay** [comment]
Well, I'll admit it's still not the best method 😆. I'll approve this because you need a functioning `-y`, but once I fix my Linux setup I'll write something cleaner :)

**Comment by RhinoCodes** [comment]
@Bobbbay its functional and im not a bash genius so xD

**Pull request merged**
